import { describe, expect, it } from 'vitest'
import type { OpenInAppIconSourceDeps } from './open-in-app-icon-source'
import {
  getMacAppBundlePath,
  resolveMacAppIconFile,
  getToolboxLauncherApplication,
  resolveOpenInAppIconSource
} from './open-in-app-icon-source'

const TOOLBOX_SCRIPT = `#!/bin/bash
#Generated by JetBrains Toolbox 3.8.1.88030

declare -a intellij_args=()
open -na "/Users/dev/Applications/GoLand.app/Contents/MacOS/goland" $wait --args "\${intellij_args[@]}"
`

describe('getMacAppBundlePath', () => {
  it('takes the bundle a binary lives inside', () => {
    expect(getMacAppBundlePath('/Applications/GoLand.app/Contents/MacOS/goland')).toBe(
      '/Applications/GoLand.app'
    )
  })

  it('accepts the bundle itself', () => {
    expect(getMacAppBundlePath('/Applications/GoLand.app')).toBe('/Applications/GoLand.app')
  })

  it('returns null outside a bundle', () => {
    expect(getMacAppBundlePath('/usr/local/bin/code')).toBeNull()
  })
})

describe('getToolboxLauncherApplication', () => {
  it('reads the application a Toolbox launcher opens', () => {
    expect(getToolboxLauncherApplication(TOOLBOX_SCRIPT)).toBe(
      '/Users/dev/Applications/GoLand.app/Contents/MacOS/goland'
    )
  })

  it('ignores a script that opens nothing', () => {
    expect(getToolboxLauncherApplication('#!/bin/bash\necho hi\n')).toBeNull()
  })
})

describe('resolveOpenInAppIconSource', () => {
  const darwin: NodeJS.Platform = 'darwin'
  const win32: NodeJS.Platform = 'win32'
  const deps = (overrides: Partial<OpenInAppIconSourceDeps> = {}): OpenInAppIconSourceDeps => ({
    platform: darwin,
    fileExists: () => true,
    readTextFile: () => TOOLBOX_SCRIPT,
    ...overrides
  })

  it('points at the product bundle a Toolbox script opens', () => {
    // Why this is the whole point: the script itself renders as a generic shell-script icon,
    // identical for every JetBrains IDE.
    expect(resolveOpenInAppIconSource('/Users/dev/.../scripts/goland', deps())).toBe(
      '/Users/dev/Applications/GoLand.app'
    )
  })

  it('uses a launcher that already lives in a bundle', () => {
    expect(
      resolveOpenInAppIconSource('/Applications/Cursor.app/Contents/MacOS/cursor', deps())
    ).toBe('/Applications/Cursor.app')
  })

  it('keeps the launcher when the named bundle is gone', () => {
    expect(
      resolveOpenInAppIconSource('/Users/dev/.../scripts/goland', deps({ fileExists: () => false }))
    ).toBe('/Users/dev/.../scripts/goland')
  })

  it('keeps the launcher when the script cannot be read', () => {
    expect(
      resolveOpenInAppIconSource(
        '/Users/dev/.../scripts/goland',
        deps({
          readTextFile: () => {
            throw new Error('EACCES')
          }
        })
      )
    ).toBe('/Users/dev/.../scripts/goland')
  })

  it('leaves non-macOS launchers alone, where the executable carries its own icon', () => {
    expect(resolveOpenInAppIconSource('C:\\tools\\goland.cmd', deps({ platform: win32 }))).toBe(
      'C:\\tools\\goland.cmd'
    )
  })
})

describe('resolveMacAppIconFile', () => {
  it('picks the icon named after the bundle, not a sibling', () => {
    // Why this case: JetBrains bundles ship frontend.icns next to the product icon, and picking
    // the wrong one would brand every IDE identically.
    expect(
      resolveMacAppIconFile('/Applications/GoLand.app', {
        readDirectory: () => ['frontend.icns', 'goland.icns', 'other.png']
      })
    ).toBe('/Applications/GoLand.app/Contents/Resources/goland.icns')
  })

  it('accepts a sole icon even when its name does not match', () => {
    expect(
      resolveMacAppIconFile('/Applications/Thing.app', { readDirectory: () => ['app.icns'] })
    ).toBe('/Applications/Thing.app/Contents/Resources/app.icns')
  })

  it('refuses to guess between several unmatched icons', () => {
    expect(
      resolveMacAppIconFile('/Applications/Thing.app', {
        readDirectory: () => ['a.icns', 'b.icns']
      })
    ).toBeNull()
  })

  it('returns null when Resources cannot be read', () => {
    expect(
      resolveMacAppIconFile('/Applications/GoLand.app', {
        readDirectory: () => {
          throw new Error('ENOENT')
        }
      })
    ).toBeNull()
  })

  it('returns null for a path that is not a bundle', () => {
    expect(resolveMacAppIconFile('/usr/local/bin/code', { readDirectory: () => [] })).toBeNull()
  })
})
